ARG SOURCE
ARG ISO
ARG VAUBAN_SHA1

FROM ${SOURCE}

ARG SOURCE
ARG ISO
ARG VAUBAN_SHA1

WORKDIR /root

RUN echo "---\n\
iso: ${ISO}\n\
vauban_branch: ${VAUBAN_SHA1}\n\
date: $(date --iso-8601=seconds)\n\
stages:\n" > /imginfo && \
    echo "---\n\
packages:\n" > /packages
