FROM docker:dind

RUN apk del busybox
RUN apk add --no-cache python3 py3-yaml bash squashfs-tools git ansible openssh-client coreutils binutils findutils jq grep file make gpg gpg-agent util-linux xxhash
RUN apk add --no-cache py3-pip py3-click
RUN pip install docker
